# Generated by Django 3.2 on 2022-12-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('Nomcant', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('N_Identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido_P', models.CharField(max_length=50)),
                ('Apellido_M', models.CharField(max_length=50)),
                ('Fecha_Nac', models.DateField()),
                ('Usu_Django', models.CharField(max_length=50)),
                ('Telf_Celular', models.CharField(max_length=15)),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.ciudad')),
                ('T_Identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.tpi')),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomprov', models.CharField(max_length=50)),
                ('Nompai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.pais')),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inic', models.DateField()),
                ('Estado', models.BooleanField(default=False)),
                ('usup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='Nomprov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.provincia'),
        ),
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inici', models.DateField()),
                ('Nom_carr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.carrera')),
                ('usua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crud.usuarios')),
            ],
        ),
    ]
